### ISSUE TITLE
catkin build not working

### ISSUE THREAD

**Issue by r3tro-t3ch** [mit-acl/dpgo_ros#1]
I'm getting following error when i try to build the package. And on inspection pose_graph_tools doesn't have PoseGraphQuery.h file.

Errors     << dpgo_ros:make /home/vishnu/Workspace/dpgo_ros_ws/logs/dpgo_ros/build.make.000.log                                                                                                                   
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/PGOAgentROS.cpp:13:10: fatal error: pose_graph_tools/PoseGraphQuery.h: No such file or directory
   13 | #include <pose_graph_tools/PoseGraphQuery.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/dpgo_ros.dir/build.make:82: CMakeFiles/dpgo_ros.dir/src/PGOAgentROS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp: In function ‘pose_graph_tools::PoseGraphEdge dpgo_ros::RelativeMeasurementToMsg(const DPGO::RelativeSEMeasurement&)’:
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp:113:7: error: ‘pose_graph_tools::PoseGraphEdge’ {aka ‘struct pose_graph_tools::PoseGraphEdge_<std::allocator<void> >’} has no member named ‘robot_from’
  113 |   msg.robot_from = m.r1;
      |       ^~~~~~~~~~
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp:114:7: error: ‘pose_graph_tools::PoseGraphEdge’ {aka ‘struct pose_graph_tools::PoseGraphEdge_<std::allocator<void> >’} has no member named ‘robot_to’
  114 |   msg.robot_to = m.r2;
      |       ^~~~~~~~
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp: In function ‘DPGO::RelativeSEMeasurement dpgo_ros::RelativeMeasurementFromMsg(const PoseGraphEdge&)’:
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp:129:19: error: ‘const PoseGraphEdge’ {aka ‘const struct pose_graph_tools::PoseGraphEdge_<std::allocator<void> >’} has no member named ‘robot_from’
  129 |   size_t r1 = msg.robot_from;
      |                   ^~~~~~~~~~
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp:130:19: error: ‘const PoseGraphEdge’ {aka ‘const struct pose_graph_tools::PoseGraphEdge_<std::allocator<void> >’} has no member named ‘robot_to’
  130 |   size_t r2 = msg.robot_to;
      |                   ^~~~~~~~
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp: In function ‘pose_graph_tools::PoseGraph dpgo_ros::TrajectoryToPoseGraphMsg(unsigned int, unsigned int, unsigned int, const Matrix&)’:
/home/vishnu/Workspace/dpgo_ros_ws/src/dpgo_ros/src/utils.cpp:225:14: error: ‘pose_graph_tools::PoseGraphNode’ {aka ‘struct pose_graph_tools::PoseGraphNode_<std::allocator<void> >’} has no member named ‘robot_id’
  225 |     node_msg.robot_id = robotID;
      |              ^~~~~~~~
make[2]: *** [CMakeFiles/dpgo_ros.dir/build.make:95: CMakeFiles/dpgo_ros.dir/src/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:486: CMakeFiles/dpgo_ros.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by yuluntian** [comment]
Hi, please make sure to use the [feature/multirobot branch](https://github.com/MIT-SPARK/pose_graph_tools/tree/feature/multirobot) of pose_graph_tools in your catkin workspace. Specifically, PoseGraphQuery is a ROS service file and is [here](https://github.com/MIT-SPARK/pose_graph_tools/blob/feature/multirobot/srv/PoseGraphQuery.srv).

**Comment by yuluntian** [comment]
Closing this issue for now.
