### ISSUE TITLE
[Bug?] No use of variable `initial_poses`?

### ISSUE THREAD

**Issue by RonghaiHe** [mit-acl/dpgo_ros#5]
Thanks for your sharing codes at first.
Maybe there is a bug in function `requestPoseGraph` of `PGOAgentROS.cpp` that variable `initial_poses` hasn't been used. Here are [codes](https://github.com/mit-acl/dpgo_ros/blob/e28f2bc27c87cc96e12d812d16ddececca995745/src/PGOAgentROS.cpp#L285-L303).

**Comment by yuluntian** [comment]
@RonghaiHe Thank you for spotting this. The code you point out intends to use poses from the front end as external initialization, but right now you are right it is not being used. Instead, dpgo will compute initialization internally (happens in this [line](https://github.com/mit-acl/dpgo_ros/blob/e28f2bc27c87cc96e12d812d16ddececca995745/src/PGOAgentROS.cpp#L348)). The best way to improve the code is to add an option to switch between external and internal initialization, but unfortunately I don't have bandwidth to implement this now. I will close this issue for now, but feel free to reopen if there are further questions.
